syntax = "All"
column_width = 120
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
quote_style = "ForceDouble"
call_parentheses = "None"
collapse_simple_statement = "Always"
space_after_function_names = "Definitions"
block_newline_gaps = "Never"

[sort_requires]
enabled = true
